on:
  push:
    paths:
      - .github/actionlint.yml
      - .github/actionlint-matcher.json
  pull_request:
    paths:
      - .github/actionlint.yml
      - .github/actionlint-matcher.json
    types: [ opened, synchronize ]

name: actionlint
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install actionlint
        shell: bash
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Add problem matcher
        run: echo "::add-matcher::.github/actionlint-matcher.json"
      - name: run actionlint
        run: ./actionlint
        shell: bash